config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
#  hello/urls.py

from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('home', views.home_page_view, name='home')
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.
#  hello/views.py

from django.shortcuts import render


def home_page_view(request):
    return render(request, 'website/home.html')

website/templates/website/layout.html
<!-- layout.html -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
    		<title>Website</title>
		{% load static %}
		<link rel="stylesheet" href="{% static 'website/css/base.css' %}">
	</head>
	<body>
	    <header class="jumbotron text-center">
			<h1>Titulo Website</h1>
			<p>Um Website Fixe</p>
			<nav>
				<a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
				<!--<a href="" class="btn btn-info"></a> -->
				<!--<a href="" class="btn btn-info"></a> -->
			</nav>
		</header>
	    <article class="container">
		<main class="col-sm-6">
			{% block main %}
			{% endblock main %}
		</main>
		<aside class="col-sm-6">
			{% load static %}
			<img src="{% static 'website/images/image.png' %}">
		</aside>
	    </article>
	    <footer>Texto rodapé</footer>
	</body>
</html>